### PR TITLE
add basic operations

### PR DESCRIPTION
**Pull request by ollevche**
This PR adds basic calculator operations to be used outside of the repository as a module.

### CODE REVIEW

**Review by mulan17 — APPROVED** [review]
The best operations!

**Review by nemolovska — APPROVED** [review]

**Comment by dariaiar** [comment]
nice job, approve

**Review by onsana — APPROVED** [review]

**Comment by VioletaNaboy** [comment]
Approve

**Review by rvxt21 — APPROVED** [review]
Super

**Comment by Stacy314** [comment]
Good job!

**Review by Stacy314 — APPROVED** [review]
Good job!

**Pull request merged**
